name: ðŸ“ Documentation
description: Report an issue related to [README](https://github.com/RiceBen/BenSerilogNlog/blob/master/README.md)
labels: ["category: documentation"]

body:
- type: markdown
  attributes:
    value: >
      #### Thank you for contributing! Before submitting a doc issue, please make sure it has no duplicate by searching through [the existing and past issues](https://github.com/RiceBen/BenSerilogNlog/issues)

- type: textarea
  attributes:
    label: Descripe the doc issue
    description: >
      Please provide a clear and concise description of what content in Company API is an issue. Note that there are multiple active branches, such as 3.4, 4.x and 5.x, so please specify the branch with the problem.
    placeholder: |
      A clear and concise description of what content in this repo is an issue.
  validations:
    required: true
- type: textarea
  attributes:
    label: Fix suggestion
    description: >
      Tell us how we could improve the documentation in this regard.